spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: authDev
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: authDev
admin:
  username: admin
  password: admin123
  email: admin@example.com
