spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/public.pem
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console